[project]
name = "emsp-portal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ivo Abdoul", email = "abdoulrhamaneivo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
emsp-portal = "emsp_portal:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
